spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: jja
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false
api:
  key: AIzaSyBm3xh9oZP1ksMWcMzVaZQevWlrtb8tIgc